language: node_js
node_js:
- '10'
deploy:
  provider: heroku
  app: runleiwang-tutorial
  api_key:
    secure: eLYlBVCccE6L7kml3IQnrnqFnhi2FD9CEPq+w1WXj6kaUsO3EREG+srzz01WkHxye9XBOQAoB9szDmPaM0VKDUc28oeUnpeqNcUgEjP68FQu3kEs/8sAxGNup1DzKlpqeWVYmey4m86SmwkJanGu7dS5fwu4VTmdebVFiuQxpCGnZeR99RKqUt3OSlrm9wpZWUrdqh9/HxoFBJydzWioIv3e9DReJTb1IBbkmp1HuVX+ByW6HAzAydxkCFPXhtcdbwgMrtd2os133seohrita6ucuR7GfwyjxZfZaWz3Ka7jNF7wHDAP/hv79wmrUIRGt3gRy4g6TT0Zin6mmMkaoSJhP7In1LrxZappZ1cCwWSszpwY5pSYchWRyaLsldxgmYUwB/7SB4K42myr7dWmQ6p1SzdtDwxUkbY3NHEoV3m+xkq5M6vEkYUdSehMi8diXk9O0oeHg8V7kofiY2fA2PmgZCwcfPManRFfMcajc9J6L1aPaO2Bp++88ilzZ+0FdPWpKxMsqKvyFIv/2O6NCGjbE8jHAcK7Ulv1OMjnSUtzUjCRpp3MXa76P9h+uOBvhuqE8c5cOVFVrQYLJGpYZcfIn9a54ZT890tePb2c0OVjvQMW/8nr1i0ZL4hYrVK2DS1NeWCPbQVLc3lZoPmwiedrPHtxoLwhJzKLF4qDkQA=
